// Code generated by protoc-gen-go. DO NOT EDIT.
// source: slave-analysis.proto

package slaveanalysis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SlaveData struct {
	Timestamp            string     `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	JobName              string     `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	HostIp               string     `protobuf:"bytes,3,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	Processes            []*Process `protobuf:"bytes,4,rep,name=processes,proto3" json:"processes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SlaveData) Reset()         { *m = SlaveData{} }
func (m *SlaveData) String() string { return proto.CompactTextString(m) }
func (*SlaveData) ProtoMessage()    {}
func (*SlaveData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f8313fb4404da07, []int{0}
}

func (m *SlaveData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlaveData.Unmarshal(m, b)
}
func (m *SlaveData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlaveData.Marshal(b, m, deterministic)
}
func (m *SlaveData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlaveData.Merge(m, src)
}
func (m *SlaveData) XXX_Size() int {
	return xxx_messageInfo_SlaveData.Size(m)
}
func (m *SlaveData) XXX_DiscardUnknown() {
	xxx_messageInfo_SlaveData.DiscardUnknown(m)
}

var xxx_messageInfo_SlaveData proto.InternalMessageInfo

func (m *SlaveData) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *SlaveData) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *SlaveData) GetHostIp() string {
	if m != nil {
		return m.HostIp
	}
	return ""
}

func (m *SlaveData) GetProcesses() []*Process {
	if m != nil {
		return m.Processes
	}
	return nil
}

type Process struct {
	ProcessName          string   `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ProcessId            int32    `protobuf:"varint,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f8313fb4404da07, []int{1}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *Process) GetProcessId() int32 {
	if m != nil {
		return m.ProcessId
	}
	return 0
}

type DataUsage struct {
	Directory            string   `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	UsedMb               float32  `protobuf:"fixed32,2,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataUsage) Reset()         { *m = DataUsage{} }
func (m *DataUsage) String() string { return proto.CompactTextString(m) }
func (*DataUsage) ProtoMessage()    {}
func (*DataUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f8313fb4404da07, []int{2}
}

func (m *DataUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataUsage.Unmarshal(m, b)
}
func (m *DataUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataUsage.Marshal(b, m, deterministic)
}
func (m *DataUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataUsage.Merge(m, src)
}
func (m *DataUsage) XXX_Size() int {
	return xxx_messageInfo_DataUsage.Size(m)
}
func (m *DataUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_DataUsage.DiscardUnknown(m)
}

var xxx_messageInfo_DataUsage proto.InternalMessageInfo

func (m *DataUsage) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *DataUsage) GetUsedMb() float32 {
	if m != nil {
		return m.UsedMb
	}
	return 0
}

type BandwithUsage struct {
	Upload               float32  `protobuf:"fixed32,1,opt,name=upload,proto3" json:"upload,omitempty"`
	Download             float32  `protobuf:"fixed32,2,opt,name=download,proto3" json:"download,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BandwithUsage) Reset()         { *m = BandwithUsage{} }
func (m *BandwithUsage) String() string { return proto.CompactTextString(m) }
func (*BandwithUsage) ProtoMessage()    {}
func (*BandwithUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f8313fb4404da07, []int{3}
}

func (m *BandwithUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BandwithUsage.Unmarshal(m, b)
}
func (m *BandwithUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BandwithUsage.Marshal(b, m, deterministic)
}
func (m *BandwithUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BandwithUsage.Merge(m, src)
}
func (m *BandwithUsage) XXX_Size() int {
	return xxx_messageInfo_BandwithUsage.Size(m)
}
func (m *BandwithUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_BandwithUsage.DiscardUnknown(m)
}

var xxx_messageInfo_BandwithUsage proto.InternalMessageInfo

func (m *BandwithUsage) GetUpload() float32 {
	if m != nil {
		return m.Upload
	}
	return 0
}

func (m *BandwithUsage) GetDownload() float32 {
	if m != nil {
		return m.Download
	}
	return 0
}

type MemoryUsage struct {
	FreeMem              int32    `protobuf:"varint,1,opt,name=free_mem,json=freeMem,proto3" json:"free_mem,omitempty"`
	TotalMem             int32    `protobuf:"varint,2,opt,name=total_mem,json=totalMem,proto3" json:"total_mem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryUsage) Reset()         { *m = MemoryUsage{} }
func (m *MemoryUsage) String() string { return proto.CompactTextString(m) }
func (*MemoryUsage) ProtoMessage()    {}
func (*MemoryUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f8313fb4404da07, []int{4}
}

func (m *MemoryUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryUsage.Unmarshal(m, b)
}
func (m *MemoryUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryUsage.Marshal(b, m, deterministic)
}
func (m *MemoryUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryUsage.Merge(m, src)
}
func (m *MemoryUsage) XXX_Size() int {
	return xxx_messageInfo_MemoryUsage.Size(m)
}
func (m *MemoryUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryUsage.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryUsage proto.InternalMessageInfo

func (m *MemoryUsage) GetFreeMem() int32 {
	if m != nil {
		return m.FreeMem
	}
	return 0
}

func (m *MemoryUsage) GetTotalMem() int32 {
	if m != nil {
		return m.TotalMem
	}
	return 0
}

func init() {
	proto.RegisterType((*SlaveData)(nil), "slaveanalysis.SlaveData")
	proto.RegisterType((*Process)(nil), "slaveanalysis.Process")
	proto.RegisterType((*DataUsage)(nil), "slaveanalysis.DataUsage")
	proto.RegisterType((*BandwithUsage)(nil), "slaveanalysis.BandwithUsage")
	proto.RegisterType((*MemoryUsage)(nil), "slaveanalysis.MemoryUsage")
}

func init() { proto.RegisterFile("slave-analysis.proto", fileDescriptor_8f8313fb4404da07) }

var fileDescriptor_8f8313fb4404da07 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcb, 0x4e, 0xf3, 0x30,
	0x14, 0x84, 0xd5, 0xf6, 0x6f, 0x2e, 0xa7, 0x7f, 0x37, 0x16, 0x2a, 0x29, 0x17, 0xa9, 0x64, 0xd5,
	0x0d, 0x5d, 0x00, 0x4f, 0x50, 0x60, 0x51, 0xa1, 0x20, 0x14, 0xc4, 0x3a, 0x72, 0xea, 0x03, 0x4d,
	0x15, 0xc7, 0x91, 0xed, 0x52, 0xf5, 0x39, 0x78, 0x61, 0xe4, 0xe3, 0x5e, 0xc4, 0x72, 0xbe, 0x39,
	0x1a, 0xcf, 0xc8, 0x70, 0x66, 0x6a, 0xfe, 0x8d, 0xb7, 0xbc, 0xe1, 0xf5, 0xce, 0x54, 0x66, 0xd6,
	0x6a, 0x65, 0x15, 0x1b, 0x12, 0x3d, 0xc0, 0xf4, 0xa7, 0x03, 0xf1, 0xbb, 0x23, 0x4f, 0xdc, 0x72,
	0x76, 0x05, 0xb1, 0xad, 0x24, 0x1a, 0xcb, 0x65, 0x9b, 0x74, 0x26, 0x9d, 0x69, 0x9c, 0x9f, 0x00,
	0x1b, 0x43, 0xb4, 0x56, 0x65, 0xd1, 0x70, 0x89, 0x49, 0x97, 0xcc, 0x70, 0xad, 0xca, 0x57, 0x2e,
	0x91, 0x9d, 0x43, 0xb8, 0x52, 0xc6, 0x16, 0x55, 0x9b, 0xf4, 0xc8, 0x09, 0x9c, 0x5c, 0xb4, 0xec,
	0x01, 0xe2, 0x56, 0xab, 0x25, 0x1a, 0x83, 0x26, 0xf9, 0x37, 0xe9, 0x4d, 0x07, 0x77, 0xa3, 0xd9,
	0x9f, 0x0a, 0xb3, 0x37, 0xef, 0xe7, 0xa7, 0xc3, 0xf4, 0x05, 0xc2, 0x3d, 0x65, 0x37, 0xf0, 0x7f,
	0xcf, 0xfd, 0xc3, 0xbe, 0xd5, 0x60, 0xcf, 0xe8, 0xf1, 0x6b, 0x80, 0xc3, 0x49, 0x25, 0xa8, 0x59,
	0xff, 0x18, 0xb6, 0x10, 0xe9, 0x1c, 0x62, 0x37, 0xee, 0xc3, 0xf0, 0x2f, 0x74, 0x0b, 0x45, 0xa5,
	0x71, 0x69, 0x95, 0xde, 0x1d, 0x16, 0x1e, 0x81, 0x9b, 0xb1, 0x31, 0x28, 0x0a, 0x59, 0x52, 0x4c,
	0x37, 0x0f, 0x9c, 0xcc, 0xca, 0xf4, 0x11, 0x86, 0x73, 0xde, 0x88, 0x6d, 0x65, 0x57, 0x3e, 0x67,
	0x04, 0xc1, 0xa6, 0xad, 0x15, 0x17, 0x14, 0xe2, 0x0e, 0x49, 0xb1, 0x0b, 0x88, 0x84, 0xda, 0x36,
	0xe4, 0xf8, 0x88, 0xa3, 0x4e, 0x9f, 0x61, 0x90, 0xa1, 0x54, 0x7a, 0xe7, 0x23, 0xc6, 0x10, 0x7d,
	0x6a, 0xc4, 0x42, 0xa2, 0xa4, 0x90, 0x7e, 0x1e, 0x3a, 0x9d, 0xa1, 0x64, 0x97, 0x10, 0x5b, 0x65,
	0x79, 0x4d, 0x9e, 0x1f, 0x14, 0x11, 0xc8, 0x50, 0x96, 0x01, 0x7d, 0xe4, 0xfd, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x9b, 0x8b, 0x79, 0x7b, 0xe0, 0x01, 0x00, 0x00,
}
